from .activities_repo import ActivitiesRepoImpl
from .contacts_read_repo import ContactsReadRepoImpl
from .contacts_repo import ContactsRepoImpl
from .deals_repo import DealsRepoImpl
from .organization_members_read_repo import OrganizationMembersReadRepoImpl
from .organizations_read_repo import OrganizationsReadRepoImpl
from .tasks_read_repo import TasksReadRepoImpl
from .tasks_repo import TasksRepoImpl
